README.md
Another columns for the contact emails is added
=> Add contributors v2

docs/src/01_introduction_and_goals.adoc
I’ve finished drafting the first section. I think it's okay, but could you please check it to make sure everything is in order and let me know if I missed anything?
=> docs: Draft 1st section of the documentation

docs/src/02_architecture_constraints.adoc
I’ve finished drafting the second section. I think it's okay, but could you please check it to make sure everything is in order and let me know if I missed anything?
=> docs: Draft 2nd section of the documentation

docs/src/05_building_block_view.adoc, docs/src/diagrams/C4_component_diagram.puml
The first draft of the Building Block View is done, lot of text is written, review it carefully and tell me your opinions about it.
Also a new PlantUML is done for the component View
=> docs: First draft of the 5th section of the documentation

docs/src/05_building_block_view.adoc, docs/src/06_runtime_view.adoc, docs/src/diagrams/C4_business_model_diagram.puml, docs/src/diagrams/C4_component_diagram.puml, docs/src/diagrams/C4_technical_context_diagram.puml, docs/src/diagrams/Sequence_diagram_Game.puml, docs/src/diagrams/Sequence_diagram_Login.puml, docs/src/diagrams/Sequence_diagram_Question_Generation.puml, docs/src/diagrams/Sequence_diagram_Registration.puml
Completed the first sketch of the documentation regarding section number 6 (runtime view). Added 4 different sequential diagrams (Registration, login, game lifecycle, question generation).
=> First draft of documentation section number 6 (runtime view) completed

docs/src/11_technical_risks.adoc
Finished the initial draft to be peer-reviewed. There is little to nothing in technical debt as nothing came to mind at this stage of development. Not many architectural decisions have been taken besides the use of previous year's project as inspiration, taking code on demand rather than as a starting point. React may have technical debt but I am unaware of its repercussions yet.
=> docs: Write initial draft of section 11

docs/src/09_architecture_decisions.adoc
The first draft of the section "Architecture decisions" is done. Not all the decisions necessary to complete this part have yet been taken. So look at what is proposed and notice if any section or relevant information is missing.
=> docs: First draft of the 9th section of the documentation 

docs/src/04_solution_strategy.adoc
Added a small description that explains the decision on the ui tool used, as well as a link to view the current state of the wireframes
=> docs: :memo: Link and update the section 4's info to the ui desing tool.

docs/src/03_context_and_scope.adoc, docs/src/08_concepts.adoc, docs/src/diagrams/S3_C4_Business_Context_Diagram.puml, docs/src/diagrams/S3_C4_Technical_Context_Diagram.puml, docs/src/diagrams/Sequence_diagram_Game.puml, docs/src/diagrams/Sequence_diagram_Login.puml, docs/src/diagrams/Sequence_diagram_Question_Generation.puml, docs/src/diagrams/Sequence_diagram_Registration.puml
Fixed the following errors related to the documentation sections 3, 6 and 8:
Section 3: New diagrams have been designed to model the business context and the technical context of the application.
Section 6: Sequence diagrams have been updated and enhanced.
Section 8: Fixed a minor change (deleted one line that didn't belong).
Everything has been corrected and updated in the same branch (docs/8-cross-cutting-concepts)
Corresponding issues:
#12 Documentation Section 3: System Scope and Context
#15 Documentation Section 6: Runtime View
=> docs: Fixed documentation errors related to sections 3, 6 and 8

gatewayservice/gateway-service.js, gatewayservice/gateway-service.test.js, questionservice/jest.config.js, questionservice/jsconfig.json, questionservice/package-lock.json, questionservice/package.json, questionservice/src/controllers/question-controller.js, questionservice/src/models/question-model.js, questionservice/src/routes/question-routes.js, questionservice/src/services/question-generator.js, questionservice/src/services/question-storage.js, questionservice/test/question-generator.test.js, webapp/src/components/GetQuestions.js
The question generation is improved, allowing to specify the type of the questions and the number of questions to be generated.
Also I implemented functionality and routes to:
- Search a question by id
- Search a random question
- Eliminate all que questions from the db 
- Get all question from the db (this has no route yet)
- Check if a selected answer is correct passing in the body the id and the asnwer selected by the user
- Add a single created question to the db (this has no route yet and it is provisional)
Also all the tests to check this funcionalities and routes are implemented (up to 16 tests of the question-service)
=> feature: Improved prototype of question service, tests and api methods of question service

gatewayservice/gateway-service.js, gatewayservice/gateway-service.test.js
The api methods required to connect frontend and question-service to deal with questions are implemented
=> feature: Api methods in gateway-service about questions

questionservice/src/services/question-generator.js
Change the generate questions so the correct answer is not always the first one
=> Change the generate questions 

webapp/src/windows/HomePage.js
Fixed the images issue in the home page. Now, icons are displayed correctly
=> Fixed the images issue in the home page

questionservice/package-lock.json, questionservice/package.json, questionservice/src/index.js, questionservice/src/models/question-model.js, questionservice/src/services/question-worker.js
Generating questions every 10 minutes is done concurrently with the application by using cron-job
=> feature: Generating questions periodically

docs/src/05_building_block_view.adoc, docs/src/diagrams/C4_business_model_diagram.puml, docs/src/diagrams/C4_component_diagram.puml, docs/src/diagrams/C4_technical_context_diagram.puml
Changes commented on class are done, the three diagrams are modified, an Gateway API between the client application and the REST API is added, also a container for the LLM Chat differing from the LLM AI API which is external
=> Fixed changes on documentation section 5

gatewayservice/openapi.yaml
Here is the missing documentation for the added functionality. When we finally add the game service, we'll need to expand it.
=> feature: First draft of the api-doc completed

webapp/src/windows/HomePage.jsx
Switched it for basic quiz in case the user does not select anything.
=> fix: fix expert domain sending "roulette" as gamemode

.github/workflows/release.yml, docker-compose.yml, gatewayservice/gateway-service.js, gatewayservice/gateway-service.test.js, webapp/package.json, webapp/src/components/AddUser.jsx, webapp/src/components/AiChat.jsx, webapp/src/components/Login.jsx, webapp/src/tests/AddUser.test.js, webapp/src/tests/AiChat.test.js, webapp/src/tests/GamePage.test.js, webapp/src/tests/HomePage.test.js, webapp/src/tests/Login.test.js, webapp/src/windows/GamePage.jsx, webapp/src/windows/Leaderboard.jsx
Only need to update the enviroment variables at the wiki and it is working.
closes #157
=> Modified the api paths, as well as the docker compose and cors setup to enable https with ngix.

docs/src/05_building_block_view.adoc, docs/src/diagrams/C4_component_diagram.puml, docs/src/diagrams/C4_technical_context_diagram.puml
The documentation of section five in now updated and up to date with our application. Check if something is missing
=> fix: documentation section 5

webapp/src/App.js, webapp/src/components/NavBarSignedIn.jsx, webapp/src/css/Leaderboard.css, webapp/src/css/Statistics.css, webapp/src/locales/EN.json, webapp/src/windows/HomePage.jsx, webapp/src/windows/Leaderboard.jsx, webapp/src/windows/Statistics.jsx
Removing the background and making the nav bar consistent between all the views. Also changed the log off button (now log out) by petition of some testers of the app. The app now looks much more integrated, as all the windows have the same styles. Also improved the red colour to make it clearly differentiable and added advanced styles to the Card components of the Leaderboard and Statistics views.
**IMPORTANT:** Functionality unchanged, all the changes performed in this PR are merely aesthetic and based on the appearance of the application.
=> Improval of the styles and consistency between views

webapp/src/css/HomePage.css, webapp/src/windows/HomePage.jsx
Now, the container of the game modes in the home page is a scrollable. This will help when extending the functionality of the application in the future (with more game modes).
=> Added carousel functionality to the home

gameservice/src/models/score-model.js, gameservice/src/routes/game-routes.js, gameservice/src/services/game-service.js, gameservice/test/game-routes.test.js, webapp/e2e/jest.config.js, webapp/src/components/GameComponent.jsx, webapp/src/locales/EN.json, webapp/src/locales/ES.json, webapp/src/windows/GamePage.jsx, webapp/src/windows/Statistics.jsx
modified how the questions calculate points, as well as the backend to save the average time to respond, and also the statistics view to show It.
=> change point system

.gitignore, questionservice/src/services/question-generator.js, questionservice/src/services/question-storage.js, questionservice/src/services/question-worker.js, questionservice/test/question-storage.test.js, questionservice/test/question-worker.test.js
The 3 remaining types of questions are generated, they are too simple as wikidata is too slow and has his problems so we cannot continue generate questions through complex queries, they should be simple and fast
=> Feature/ new question types
